### ISSUE TITLE
hello，this is project based on which version of NS3?

### ISSUE THREAD

**Issue by DaoiestFire** [truthatt11/leach-in-ns3#1]

**Comment by truthatt11** [comment]
It seems to be 3.26
Which version of ns3 do you use? this repo has not maintained for a long time

**Comment by ares1876** [comment]
Hello. 
I tried to build your module on 3.29 version, but i gives me an error "error finding headers for module leach-in-ns3". Unforntunately it does not show any further information on headers.
Do you have any idea which modules might be missing or how to resolve this error

**Comment by ares1878** [comment]
Hello.
I cloned this repo into the '/src' directory of ns3 (v. 29). I renamed it to "leach" (since this is the name used for the module in wscript). Then when i try "./build.py" command to build the new module, i have the following error. Can you please suggest me how can i make this work? I also tried to install ns3.26 but it also fails to install due to some errors in "wimax" module. Thank you in advance.

[1790/2646] Compiling src/leach/model/leach-routing-protocol.cc
In file included from ./ns3/object-base.h:23,
                 from ./ns3/object.h:29,
                 from ./ns3/ipv4.h:24,
                 from ../src/leach/model/leach-rtable.h:38,
                 from ../src/leach/model/leach-routing-protocol.h:36,
                 from ../src/leach/model/leach-routing-protocol.cc:33:
./ns3/type-id.h: In instantiation of ‘static ns3::ObjectBase* ns3::TypeId::AddConstructor()::Maker::Create() [with T = ns3::leach::RoutingProtocol]’:
./ns3/type-id.h:659:3:   required from ‘ns3::TypeId ns3::TypeId::AddConstructor() [with T = ns3::leach::RoutingProtocol]’
../src/leach/model/leach-routing-protocol.cc:77:39:   required from here
./ns3/type-id.h:656:27: error: invalid new-expression of abstract class type ‘ns3::leach::RoutingProtocol’
  656 |       ObjectBase * base = new T ();
      |                           ^~~~~~~~
In file included from ../src/leach/model/leach-routing-protocol.cc:33:
../src/leach/model/leach-routing-protocol.h:64:7: note:   because the following virtual functions are pure within ‘ns3::leach::RoutingProtocol’:
   64 | class RoutingProtocol : public Ipv4RoutingProtocol
      |       ^~~~~~~~~~~~~~~
In file included from ../src/leach/model/leach-packet-queue.h:36,
                 from ../src/leach/model/leach-routing-protocol.h:37,
                 from ../src/leach/model/leach-routing-protocol.cc:33:
./ns3/ipv4-routing-protocol.h:172:16: note:     ‘virtual void ns3::Ipv4RoutingProtocol::PrintRoutingTable(ns3::Ptr<ns3::OutputStreamWrapper>, ns3::Time::Unit) const’
  172 |   virtual void PrintRoutingTable (Ptr<OutputStreamWrapper> stream, Time::Unit unit = Time::S) const = 0;
      |                ^~~~~~~~~~~~~~~~~

Waf: Leaving directory `/home/kali/workspace/ns-allinone-3.29/ns-3.29/build'                                                                        
Build failed
 -> task in 'ns3-leach' failed with exit status 1 (run with -v to display more information)                                                         
Traceback (most recent call last):
  File "./build.py", line 176, in <module>
    sys.exit(main(sys.argv))
  File "./build.py", line 167, in main
    build_ns3(config, build_examples, build_tests, args, build_options)
  File "./build.py", line 87, in build_ns3
    run_command([sys.executable, "waf", "build"] + build_options)
  File "/home/kali/workspace/ns-allinone-3.29/util.py", line 25, in run_command
    raise CommandError("Command %r exited with code %i" % (argv, retval))
util.CommandError: Command ['/usr/bin/python', 'waf', 'build'] exited with code 1

**Comment by mnaderi1989** [comment]
> Hello.
> I cloned this repo into the '/src' directory of ns3 (v. 29). I renamed it to "leach" (since this is the name used for the module in wscript). Then when i try "./build.py" command to build the new module, i have the following error. Can you please suggest me how can i make this work? I also tried to install ns3.26 but it also fails to install due to some errors in "wimax" module. Thank you in advance.
> 
> [1790/2646] Compiling src/leach/model/leach-routing-protocol.cc
> In file included from ./ns3/object-base.h:23,
> from ./ns3/object.h:29,
> from ./ns3/ipv4.h:24,
> from ../src/leach/model/leach-rtable.h:38,
> from ../src/leach/model/leach-routing-protocol.h:36,
> from ../src/leach/model/leach-routing-protocol.cc:33:
> ./ns3/type-id.h: In instantiation of ‘static ns3::ObjectBase* ns3::TypeId::AddConstructor()::Maker::Create() [with T = ns3::leach::RoutingProtocol]’:
> ./ns3/type-id.h:659:3: required from ‘ns3::TypeId ns3::TypeId::AddConstructor() [with T = ns3::leach::RoutingProtocol]’
> ../src/leach/model/leach-routing-protocol.cc:77:39: required from here
> ./ns3/type-id.h:656:27: error: invalid new-expression of abstract class type ‘ns3::leach::RoutingProtocol’
> 656 | ObjectBase * base = new T ();
> | ^~~~~~~~
> In file included from ../src/leach/model/leach-routing-protocol.cc:33:
> ../src/leach/model/leach-routing-protocol.h:64:7: note: because the following virtual functions are pure within ‘ns3::leach::RoutingProtocol’:
> 64 | class RoutingProtocol : public Ipv4RoutingProtocol
> | ^~~~~~~~~~~~~~~
> In file included from ../src/leach/model/leach-packet-queue.h:36,
> from ../src/leach/model/leach-routing-protocol.h:37,
> from ../src/leach/model/leach-routing-protocol.cc:33:
> ./ns3/ipv4-routing-protocol.h:172:16: note: ‘virtual void ns3::Ipv4RoutingProtocol::PrintRoutingTable(ns3::Ptrns3::OutputStreamWrapper, ns3::Time::Unit) const’
> 172 | virtual void PrintRoutingTable (Ptr stream, Time::Unit unit = Time::S) const = 0;
> | ^~~~~~~~~~~~~~~~~
> 
> Waf: Leaving directory `/home/kali/workspace/ns-allinone-3.29/ns-3.29/build'
> Build failed
> -> task in 'ns3-leach' failed with exit status 1 (run with -v to display more information)
> Traceback (most recent call last):
> File "./build.py", line 176, in
> sys.exit(main(sys.argv))
> File "./build.py", line 167, in main
> build_ns3(config, build_examples, build_tests, args, build_options)
> File "./build.py", line 87, in build_ns3
> run_command([sys.executable, "waf", "build"] + build_options)
> File "/home/kali/workspace/ns-allinone-3.29/util.py", line 25, in run_command
> raise CommandError("Command %r exited with code %i" % (argv, retval))
> util.CommandError: Command ['/usr/bin/python', 'waf', 'build'] exited with code 1

Hi ares1878
how did you solved this error? I have simlilar error in adding a new module in ns-3.

**Comment by truthatt11** [comment]
The current model can not fit ns 3.29
The wifi model has changed a little bit
I think I can rewrite the "Other models modified" to a more compatible version

**Comment by truthatt11** [comment]
> ? I also tried to install ns3.26 but it also fails to install due to some errors in "wimax" module. Thank you in advance.

Copy the 2 folders in "Other models modified" and overwrite them in "src"
There are some changes
